#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:20:00
#SBATCH -J RNA_qualitycheck_job
#SBATCH --mail-type=ALL
#SBATCH --mail-user anna2860@student.uu.se
#SBATCH --output=%x.%j.out

# Load modules
module load bioinfo-tools
module load samtools
module load FastQC

#run fastQC

fastqc /home/anirudh/GA_Lab/RNA_trimmed/SRR4342137_1_trimmed.fastq.gz -o /home/anirudh/GA_Lab/RNA_QC
fastqc /home/anirudh/GA_Lab/RNA_trimmed/SRR4342137_1_unpaired.fastq.gz -o /home/anirudh/GA_Lab/RNA_QC
fastqc /home/anirudh/GA_Lab/RNA_trimmed/SRR4342137_2_trimmed.fastq.gz -o /home/anirudh/GA_Lab/RNA_QC
fastqc /home/anirudh/GA_Lab/RNA_trimmed/SRR4342137_2_unpaired.fastq.gz -o /home/anirudh/GA_Lab/RNA_QC
fastqc /home/anirudh/GA_Lab/RNA_trimmed/SRR4342139_1_trimmed.fastq.gz -o /home/anirudh/GA_Lab/RNA_QC
fastqc /home/anirudh/GA_Lab/RNA_trimmed/SRR4342139_1_unpaired.fastq.gz -o /home/anirudh/GA_Lab/RNA_QC
fastqc /home/anirudh/GA_Lab/RNA_trimmed/SRR4342139_2_trimmed.fastq.gz -o /home/anirudh/GA_Lab/RNA_QC
fastqc /home/anirudh/GA_Lab/RNA_trimmed/SRR4342139_2_unpaired.fastq.gz -o /home/anirudh/GA_Lab/RNA_QC
