#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:20:00
#SBATCH -J untrimmed_qc_job
#SBATCH --mail-type=ALL
#SBATCH --mail-user anna2860@student.uu.se
#SBATCH --output=%x.%j.out

# Load modules
module load bioinfo-tools
module load samtools
module load FastQC

#run fastQC

fastqc /home/anirudh/GA_Lab/untrimmed/SRR4342137.1.fastq.gz /home/anirudh/GA_Lab/untrimmed/SRR4342137.2.fastq.gz -o /home/anirudh/GA_Lab/untrimmed
fastqc /home/anirudh/GA_Lab/untrimmed/SRR4342139.1.fastq.gz /home/anirudh/GA_Lab/untrimmed/SRR4342139.2.fastq.gz -o /home/anirudh/GA_Lab/untrimmed
